import type { Product } from "@/types/product"

// Mock data for financial products
const products: Product[] = [
  {
    id: "1",
    name: "Cuenta Digital Plus",
    type: "Cuenta",
    category: "Cuentas",
    description: "Cuenta digital sin comisiones con tarjeta de débito internacional y beneficios exclusivos.",
    interestRate: 1.2,
    features: [
      "Sin comisiones de mantenimiento",
      "Tarjeta de débito internacional",
      "Retiros gratuitos en cajeros",
      "Transferencias SPEI sin costo",
      "App móvil con control total",
      "Notificaciones en tiempo real",
    ],
    requirements: [
      "Identificación oficial vigente",
      "Comprobante de domicilio (no mayor a 3 meses)",
      "Ser mayor de 18 años",
    ],
  },
  {
    id: "2",
    name: "Tarjeta Platinum Rewards",
    type: "Tarjeta de Crédito",
    category: "Tarjetas",
    description:
      "Tarjeta de crédito premium con programa de recompensas y beneficios exclusivos para viajeros frecuentes.",
    interestRate: 24.9,
    features: [
      "Acumulación de 2 puntos por cada $1 gastado",
      "Acceso a salas VIP en aeropuertos",
      "Seguro de viaje internacional",
      "Protección de compras",
      "Sin comisión anual el primer año",
      "Descuentos en restaurantes selectos",
    ],
    requirements: [
      "Ingresos mínimos de $35,000 mensuales",
      "Historial crediticio favorable",
      "Identificación oficial vigente",
      "Comprobante de ingresos",
    ],
  },
  {
    id: "3",
    name: "Fondo de Inversión Equilibrado",
    type: "Inversión",
    category: "Inversiones",
    description:
      "Fondo de inversión diversificado con balance entre renta fija y variable para un crecimiento estable a mediano plazo.",
    riskLevel: 3,
    minimumInvestment: 5000,
    term: "Mediano plazo (3-5 años)",
    features: [
      "Diversificación en múltiples instrumentos",
      "Gestión profesional del portafolio",
      "Liquidez semanal",
      "Reportes trimestrales detallados",
      "Asesoría personalizada",
      "Reinversión automática de rendimientos",
    ],
    requirements: [
      "Inversión mínima de $5,000",
      "Identificación oficial vigente",
      "Comprobante de domicilio",
      "Completar perfil de riesgo",
    ],
  },
  {
    id: "4",
    name: "Seguro de Vida Integral",
    type: "Seguro",
    category: "Seguros",
    description: "Seguro de vida con cobertura amplia y beneficios adicionales para protección familiar completa.",
    features: [
      "Cobertura por fallecimiento",
      "Indemnización por invalidez",
      "Gastos funerarios incluidos",
      "Asistencia médica telefónica",
      "Adelanto por enfermedades graves",
      "Ajuste anual por inflación",
    ],
    requirements: [
      "Edad entre 18 y 65 años",
      "Identificación oficial vigente",
      "Cuestionario médico básico",
      "Beneficiarios designados",
    ],
  },
  {
    id: "5",
    name: "Hipoteca Flexible",
    type: "Hipoteca",
    category: "Préstamos",
    description: "Crédito hipotecario con tasas competitivas y opciones de pago flexibles para la compra de vivienda.",
    interestRate: 8.5,
    term: "Hasta 20 años",
    features: [
      "Tasa fija durante toda la vida del crédito",
      "Financiamiento hasta del 80% del valor del inmueble",
      "Pagos anticipados sin penalización",
      "Seguro de daños incluido",
      "Plazos de 5 a 20 años",
      "Posibilidad de reestructuración",
    ],
    requirements: [
      "Historial crediticio favorable",
      "Ingresos comprobables",
      "Antigüedad laboral mínima de 2 años",
      "Enganche mínimo del 20%",
      "Propiedad en zonas autorizadas",
    ],
  },
  {
    id: "6",
    name: "Préstamo Personal Exprés",
    type: "Préstamo",
    category: "Préstamos",
    description: "Préstamo personal de rápida aprobación para emergencias o proyectos a corto plazo.",
    interestRate: 16.9,
    term: "12 a 36 meses",
    features: [
      "Aprobación en 24 horas",
      "Sin garantía ni aval",
      "Montos desde $5,000 hasta $150,000",
      "Tasa fija durante todo el plazo",
      "Sin penalización por pago anticipado",
      "Depósito directo a tu cuenta",
    ],
    requirements: [
      "Edad entre 21 y 70 años",
      "Ingresos mínimos de $10,000 mensuales",
      "Identificación oficial vigente",
      "Comprobante de ingresos",
      "Antigüedad laboral mínima de 1 año",
    ],
  },
  {
    id: "7",
    name: "Fondo de Inversión Agresivo",
    type: "Inversión",
    category: "Inversiones",
    description: "Fondo de inversión enfocado en renta variable con alto potencial de rendimiento a largo plazo.",
    riskLevel: 5,
    minimumInvestment: 10000,
    term: "Largo plazo (5+ años)",
    features: [
      "Exposición a mercados internacionales",
      "Enfoque en sectores de alto crecimiento",
      "Gestión activa del portafolio",
      "Reportes mensuales de desempeño",
      "Asesoría especializada",
      "Acceso a IPOs selectas",
    ],
    requirements: [
      "Inversión mínima de $10,000",
      "Horizonte de inversión de largo plazo",
      "Tolerancia alta al riesgo",
      "Experiencia previa en inversiones",
    ],
  },
  {
    id: "8",
    name: "Cuenta de Ahorro Programado",
    type: "Cuenta",
    category: "Cuentas",
    description:
      "Cuenta de ahorro con depósitos programados y restricciones de retiro para fomentar el ahorro disciplinado.",
    interestRate: 3.5,
    features: [
      "Tasa de interés preferencial",
      "Depósitos automáticos programados",
      "Restricciones de retiro personalizables",
      "Metas de ahorro visuales",
      "Bonificación por cumplimiento de metas",
      "Sin comisiones de mantenimiento",
    ],
    requirements: [
      "Cuenta principal activa",
      "Depósito inicial mínimo de $1,000",
      "Compromiso de depósitos mensuales",
      "Identificación oficial vigente",
    ],
  },
  {
    id: "9",
    name: "Seguro de Auto Premium",
    type: "Seguro",
    category: "Seguros",
    description: "Seguro de automóvil con cobertura amplia y servicios adicionales para una protección completa.",
    features: [
      "Cobertura de daños materiales",
      "Responsabilidad civil amplia",
      "Robo total",
      "Asistencia vial 24/7",
      "Auto sustituto",
      "Gastos médicos para ocupantes",
      "Defensa legal",
    ],
    requirements: [
      "Automóvil con antigüedad menor a 10 años",
      "Tarjeta de circulación vigente",
      "Identificación oficial del propietario",
      "Inspección física del vehículo",
    ],
  },
  {
    id: "10",
    name: "Tarjeta Business Elite",
    type: "Tarjeta de Crédito",
    category: "Tarjetas",
    description: "Tarjeta de crédito empresarial con beneficios especializados para negocios y control de gastos.",
    interestRate: 22.5,
    features: [
      "Emisión de tarjetas adicionales con límites personalizados",
      "Reportes detallados de gastos por categoría",
      "Integración con software contable",
      "Acumulación de puntos en compras de negocio",
      "Seguro de protección de compras",
      "Asistencia para viajes de negocios",
    ],
    requirements: [
      "Negocio establecido con mínimo 2 años de operación",
      "Ingresos anuales demostrables",
      "Buen historial crediticio",
      "Documentación legal del negocio",
    ],
  },
  {
    id: "11",
    name: "Fondo de Inversión Conservador",
    type: "Inversión",
    category: "Inversiones",
    description:
      "Fondo de inversión de bajo riesgo enfocado en instrumentos de deuda gubernamental y corporativa de alta calidad.",
    riskLevel: 1,
    minimumInvestment: 1000,
    term: "Corto plazo (1-2 años)",
    features: [
      "Preservación de capital",
      "Rendimientos estables",
      "Alta liquidez",
      "Diversificación en instrumentos de deuda",
      "Reportes mensuales",
      "Disponibilidad de recursos en 48 horas",
    ],
    requirements: [
      "Inversión mínima de $1,000",
      "Identificación oficial vigente",
      "Comprobante de domicilio",
      "Cuenta bancaria para transferencias",
    ],
  },
  {
    id: "12",
    name: "Préstamo Automotriz",
    type: "Préstamo Automotriz",
    category: "Préstamos",
    description: "Financiamiento para la adquisición de vehículos nuevos con tasas preferenciales y plazos flexibles.",
    interestRate: 10.9,
    term: "Hasta 60 meses",
    features: [
      "Financiamiento hasta del 90% del valor del vehículo",
      "Tasa fija durante todo el plazo",
      "Pagos fijos mensuales",
      "Seguro de auto con descuento",
      "Sin penalización por pagos anticipados",
      "Trámites simplificados",
    ],
    requirements: [
      "Edad entre 21 y 65 años",
      "Ingresos mínimos de $15,000 mensuales",
      "Historial crediticio favorable",
      "Enganche mínimo del 10%",
      "Identificación oficial vigente",
    ],
  },
]

export function getProducts(): Product[] {
  return products
}

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id)
}
